package com.bt.nextgen.api.draftaccount;

/**
 * Constants to be used in logging
 *
 */
public interface LoggingConstants {
    //
    String ONBOARDING = "ONBOARDING_LOGGING";
    String ONBOARDING_DELIMITER = "::";
    String DEPOSITS_SUBMIT = "DEPOSITS_LOGGING_SUBMIT" + ONBOARDING_DELIMITER;
    String PAYMENTS_SUBMIT = "PAYMENTS_LOGGING_SUBMIT" + ONBOARDING_DELIMITER;
    String ONBOARDING_SEND = ONBOARDING + ONBOARDING_DELIMITER + "SEND" + ONBOARDING_DELIMITER;
    String ONBOARDING_APPROVAL = ONBOARDING + ONBOARDING_DELIMITER + "APPROVAL" + ONBOARDING_DELIMITER;
    String ONBOARDING_WITHDRAWAL = ONBOARDING + ONBOARDING_DELIMITER + "WITHDRAWAL" + ONBOARDING_DELIMITER;
    String ONBOARDING_DELETE = ONBOARDING + ONBOARDING_DELIMITER + "DELETE" + ONBOARDING_DELIMITER;
    String ONBOARDING_CREATE = ONBOARDING + ONBOARDING_DELIMITER + "CREATE" + ONBOARDING_DELIMITER;
    String ONBOARDING_UPDATE = ONBOARDING + ONBOARDING_DELIMITER + "UPDATE" + ONBOARDING_DELIMITER;
    String ONBOARDING_SUBMIT = ONBOARDING + ONBOARDING_DELIMITER + "SUBMIT" + ONBOARDING_DELIMITER;
    String DIRECT_ONBOARDING = "DIRECT_ONBOARDING_LOGGING";
    String DIRECT_ONBOARDING_TRACKING = DIRECT_ONBOARDING + ONBOARDING_DELIMITER + "TRACKING" + ONBOARDING_DELIMITER;
    String DIRECT_ONBOARDING_CREATE =
            DIRECT_ONBOARDING + ONBOARDING_DELIMITER + "CREATE" + ONBOARDING_DELIMITER;
    String DIRECT_ONBOARDING_SUBMIT =
            DIRECT_ONBOARDING + ONBOARDING_DELIMITER + "SUBMIT" + ONBOARDING_DELIMITER;
    String PAYMENTS_DELIMITER = "-";
}
