version: '2'

networks:
  default:
    driver: overlay

services:
  mock-avaloq-icc-gateway:
    image: docker.cloud.btfin-dev.com/panorama/mock-avaloq-icc-gateway:latest
    ports:
    - "8080"
    environment:
    - JAVA_OPTS="-Xmx4012m"
    - USE_DB=canary
    - JDBC_URL=jdbc:oracle:thin:@abs:1522:${SID}
    - JDBC_USER=i_nextgen_webui
    - JDBC_PASSWORD=I_NEXTGEN_WEBUI_pwd
    labels:
      SERVICE_TAGS: urlprefix-${STACK}.${ENVIRONMENT}.cloud.btfin-dev.com/mock-avaloq-icc-gateway/
      SERVICE_CHECK_TCP: "true"
      SERVICE_INTERVAL: 5s
      SERVICE_NAME: ${STACK}-gateway
      com.btfin.devops.name: mock-gateway
      com.btfin.devops.name.group: ${STACK}
  settings:
    image: docker.cloud.btfin-dev.com/panorama/packaging-dagger:dagger-b496
    environment:
    - ENV=dynamic
    labels:
    - io.rancher.container.start_once=true
  mock-webseal:
    image: docker.cloud.btfin-dev.com/dev-tools/mock-webseal
    ports:
    - "80"
    environment:
      - SERVER_REDIRECT=${STACK}.${ENVIRONMENT}.cloud.btfin-dev.com/nextgen
    labels:
      SERVICE_80_TAGS: urlprefix-${STACK}.${ENVIRONMENT}.cloud.btfin-dev.com/
      SERVICE_80_CHECK_TCP: "true"
      SERVICE_80_INTERVAL: 5s
      SERVICE_80_NAME: ${STACK}-mock-webseal
      SERVICE_443_IGNORE: "true"
  nextgen:
    image: docker.cloud.btfin-dev.com/panorama/server-2.7:b580
    ports:
    - "8080"
    volumes_from:
    - settings
    environment:
    - SHARED_LOADER=/settings
    - JAVA_OPTS="-Xmx8024m"
    - WAIT_FOR_ABS=true
    labels:
      #note - required to make volumes_from: work - this is a rancher 'feature'.
      io.rancher.sidekicks: settings
      SERVICE_TAGS: urlprefix-${STACK}.${ENVIRONMENT}.cloud.btfin-dev.com/nextgen
      SERVICE_CHECK_TCP: "true"
      SERVICE_INTERVAL: 5s
      SERVICE_NAME: ${STACK}-nextgen
      com.btfin.devops.name: nextgen
      com.btfin.devops.name.group: ${STACK}
  abs-check:
    image: docker.cloud.btfin-dev.com/panorama/abs-pre-checks
    environment:
    - WEBUI_LOGIN=I_NEXTGEN_WEBUI
    - WEBUI_PASSWORD=I_NEXTGEN_WEBUI_pwd
    - K_LOGIN=k
    - K_PASSWORD=k
    - JDBC_URL="jdbc:oracle:thin:@abs:1522:${SID}"
    - HOSTNAME=abs
    - PORT=1522
    - ORACLE_SID=${SID}
    labels:
    - io.rancher.container.start_once=true

  abs:
    image: docker.cloud.btfin-dev.com/panorama/abs-guest
    command: /home/oracle/bin/run.sh ${ABS_BUILD}
    hostname: ${SID}
    tty: true
    stdin_open: true
    ipc: host
    ports:
      - "1522"
    environment:
      - SID=${SID}
      - "constraint:com.btfin.devops.abs==true"
    labels:
      io.rancher.scheduler.affinity:host_label: disk=large
      SERVICE_TAGS: ${SID},${ABS_BUILD},${STACK}
      SERVICE_1522_CHECK_TCP: "true"
      SERVICE_INTERVAL: 5s
      SERVICE_1522_NAME: ${STACK}-abs-${SID}
      SERVICE_1521_IGNORE: "true"
    volumes:
      - /data/${STACK}:/data
      - /adaimnt:/adaimnt
      - /var_adaimnt:/var_adaimnt
#  login-page-test:
#    image: docker.cloud.btfin-dev.com/panorama/login-page-test:LATEST
#    environment:
#     - SERVER=${DOMAIN}/nextgen
