--This script should be run in PRODUCTION environment & SVP environment for ICC user to grant access to Onboarding stored procedures and tables
--After running this script once, it will be re-run whenever there is a change.
--Version 0.1
--FOR PER_OWNER SCHEMA --
ALTER SESSION SET CURRENT_SCHEMA = PER_OWNER;

GRANT SELECT, UPDATE, INSERT ON ONBOARDING_APPLICATION TO SRVC_ICC_ONB;
GRANT SELECT, UPDATE, INSERT ON ONBOARDING_ACCOUNT TO SRVC_ICC_ONB ;
GRANT SELECT, UPDATE, INSERT ON ONBOARDING_PARTY TO SRVC_ICC_ONB;
GRANT EXECUTE ON ONBOARDING_ID_UPDATES TO SRVC_ICC_ONB;
GRANT EXECUTE ON ONBOARDING_STATUS_UPDATES TO SRVC_ICC_ONB;
GRANT SELECT, UPDATE, INSERT ON ONBOARDING_COMMUNICATION TO SRVC_ICC_ONB;
GRANT EXECUTE ON COMMUNICATION TO SRVC_ICC_ONB;