package com.bt.nextgen.core.security;

public enum UserRoles {
    USER_ROLE_ADVISER,
    USER_ROLE_ASSIST,
    USER_ROLE_PARAPLANNER,
    USER_ROLE_DEALER_GROUP,
    USER_ROLE_INVESTOR,
    USER_ROLE_SERVICE_OP,
    USER_ROLE_SERVICE_OP_CSD,
    USER_ROLE_SERVICE_OP_CRADMIN,
    USER_ROLE_SERVICE_OP_CROPS,
    USER_ROLE_SERVICE_OP_ECM,
    USER_ROLE_SERVICE_OP_ACE,
    USER_ROLE_SERVICE_OP_PROD,
    USER_ROLE_SERVICE_OP_ITSUPP,
    USER_ROLE_SERVICE_OP_CSDA,
    USER_ROLE_SUPER_USER,
    USER_ROLE_TRUSTEE,
    USER_ROLE_PORTFOLIO_MANAGER;
}
