package com.bt.nextgen.core.web.interceptor;

import java.util.Date;

import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionListener;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class listens to the session events generated by the container
 */
public class LogsSessionEvents implements HttpSessionListener
{
	private static final Logger logger = LoggerFactory.getLogger(LogsSessionEvents.class);

	@Override public void sessionCreated(HttpSessionEvent e)
	{
		HttpSession session = e.getSession();
		if (logger.isInfoEnabled()) {
			logger.info("session created {} {}", session.getId(), session.getMaxInactiveInterval());
		}
	}

	@Override public void sessionDestroyed(HttpSessionEvent e)
	{
		HttpSession session = e.getSession();
		if (logger.isInfoEnabled()) {
			logger.info("session destroyed {} created: {} last accessed: {}", session.getId(), new Date(session.getCreationTime()), new Date(session.getLastAccessedTime()));
		}

	}
}
