/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : M034259
 * Created : 11/22/2012
 */

package com.bt.nextgen.domain;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

import org.junit.Test;

import com.bt.nextgen.core.domain.BaseStringType;

public class BaseStringTypeTest
{

	@Test
	public void startWithTest()
	{
		BaseStringType tom = new BaseStringType("tom")
		{

		};
		BaseStringType tomorrow = new BaseStringType("tomorrow")
		{

		};

		assertThat(tomorrow.startsWith(tom), is(true));
		assertThat(tom.startsWith(tomorrow), is(false));

	}
}
