package com.bt.nextgen.api.draftaccount.model.form.v1;

import com.bt.nextgen.api.draftaccount.model.form.*;
import com.bt.nextgen.api.draftaccount.schemas.v1.base.AnswerTypeEnum;
import com.bt.nextgen.api.draftaccount.schemas.v1.company.CompanyDetails;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Created by m040398 on 18/03/2016.
 *
 * ICompanyForm implementation using companySchema.json autogenerated POJO (CompanyDetails)
 */
class CompanyForm implements ICompanyForm {

    private final CompanyDetails company;
    private final Integer index;

    public CompanyForm(Integer index, CompanyDetails company) {
        this.index = index;
        this.company = company;
    }

    @Override
    public String getAsicName() {
        return this.company.getAsicregisteredname();
    }

    @Override
    public IAddressForm getPlaceOfBusinessAddress() {
        if(this.company.getPlaceofbusinessv2() != null){
            return new AddressForm(this.company.getPlaceofbusinessv2());
        }
        return new AddressForm(this.company.getPlaceofbusiness());
    }

    @Override
    public String getOccupierName() {
        return this.company.getOccupiername();
    }

    @Override
    public Boolean getPersonalInvestmentEntity() {
        return company.getPersonalinvestmententity();
    }

    @Override
    public OrganisationType getOrganisationType() {
        return OrganisationType.COMPANY;
    }

    @Override
    public IAddressForm getRegisteredAddress() {
        if(this.company.getCompanyofficev2() != null){
            return new AddressForm(this.company.getCompanyofficev2());
        }
        return new AddressForm(this.company.getCompanyoffice());
    }

    @Override
    public String getABN() {
        return this.company.getCompanyabn();
    }

    @Override
    public String getACN() {
        return this.company.getAcn();
    }

    @Override
    public String getName() {
        return this.company.getCompanyname();
    }

    @Override
    public Boolean getRegisteredForGST() {
        return AnswerTypeEnum.YES.equals(this.company.getRegisteredforgst());
    }

    @Override
    public String getAnzsicCode() {
        if (this.company.getIndustry() != null) {
            return this.company.getIndustry().getAnzsiccode();
        }
        return null;
    }

    @Override
    public String getIndustryUcmCode() {
        if (this.company.getIndustry() != null) {
            return this.company.getIndustry().getUcmcode();
        }
        return null;
    }

    /**
     * @deprecated
     * @return
     */
    @Override
    @Deprecated
    public String getCisKey() {
        return null;  //we don;t have ciskey in the JSON schema v1
    }

    @Override
    public ITaxDetailsForm getTaxDetails() {
        return new TaxDetailsForm(company.getTfn(), company.getExemptionreason(), company.getTaxcountry(),company.getTaxoption());
    }

    @Override
    public ICrsTaxDetailsForm getCrsTaxDetails() {
        return (null!=company && null!= company.getTaxdetails()) ? new CrsTaxDetailsForm(company.getTaxdetails()) : null;
    }

    /**
     * @deprecated
     * @return
     */
    @Override
    @Deprecated
    public XMLGregorianCalendar getDateOfRegistration() {
        return null; //no field in company schema v1
    }

    /**
     * @deprecated
     *
     * @return
     */
    @Override
    @Deprecated
    public String getRegistrationState() {
        return null; //does not exists in company schema v1
    }

    @Override
    public boolean hasSourceOfWealth() {
        return getSourceOfWealth() != null;
    }

    @Override
    public String getSourceOfWealth() {
        return this.company.getWealthsource();
    }

    @Override
    public String getAdditionalSourceOfWealth() {
        return this.company.getAdditionalsourceofwealth();
    }

    @Override
    public boolean hasIDVDocument() {
        return false; //same as the CopnayForm impl using Map
    }

    @Override
    public RegulatoryBody getRegulatoryBody() {
        return RegulatoryBody.ASIC;
    }

    @Override
    public String getIDVDocIssuer() {
        return company.getDocissuer();
    }

    /**
     * we always map a single SMSF/Trustee/Company object into the  InvolvedPartyDetailsType. <br>
     *  Because we map a single element  ... the sequence number will always be “1” for each of them 
     * @return
     */
    @Override
    public Integer getCorrelationSequenceNumber() {
        return index;
    }
}
