#!/bin/bash
set -e

GIT_TAG=$(git rev-parse --short HEAD)
TAG=${GO_PIPELINE_LABEL:-$GIT_TAG}
DOCKER_FILE=${3:-Dockerfile}

echo "Tagging image as ${TAG}..."
docker build --pull --tag ${1}:${TAG} -f ${DOCKER_FILE} ${2}

docker push ${1}:${TAG}

docker tag -f ${1}:${TAG} ${1}

docker push ${1}

echo "${1}:${TAG}" > docker-image.txt
