<BPayPaymentRequest xmlns="ns://btfin.com/nextgen/services/schemas">
	<PaymentInstruction>
		<PaymentInstructionSystem>
			<ProductCode>${productCode}</ProductCode>
			<ProductCodeIssuer>${productCodeIssuer}</ProductCodeIssuer>
		</PaymentInstructionSystem>
		<PaymentCategory>${paymentCategory}</PaymentCategory>
		<PaymentSubCategory>${paymentSubCategory}</PaymentSubCategory>
		<PaymentCreationDateTime>${todayDate}</PaymentCreationDateTime>
		<PaymentAmount>${amount}</PaymentAmount>
		<PaymentReferenceNumber>${paymentReferenceNumber}</PaymentReferenceNumber>
		<PaymentRemitterIdentifier>${paymentRemitterIdentifier}</PaymentRemitterIdentifier>
		<PaymentDescription>${shortDescription}</PaymentDescription>
		<PaymentNarrative>${longDescription}</PaymentNarrative>
		<CreditDebitIndicator>${creditDebitIndicator}</CreditDebitIndicator>
		<DebtorAccount>
			<FinancialInstitutionAccount>
				<AccountNumber>${fromAccountNumber}</AccountNumber>
				<AccountName>${fromName}</AccountName>
				<BSB>${fromBsb}</BSB>
				<Narrative>${fromNarrative}</Narrative>
			</FinancialInstitutionAccount>
		</DebtorAccount>
		<CreditorAccount>
        			<FinancialInstitutionAccount>
        				<AccountNumber>${toAccountNumber}</AccountNumber>
        				<AccountName>${toName}</AccountName>
        				<BSB>${toBsb}</BSB>
        				<Narrative>toNarrative</Narrative>
        			</FinancialInstitutionAccount>
        </CreditorAccount>
		<PaymentType>
			<BPay>
				<Code>billerCode</Code>
				<Name>billerName</Name>
				<CRN>customerReference</CRN>
			</BPay>
		</PaymentType>
		<PaymentDate>
			<RecurringPaymentDate>
				<PaymentStartDate>${paymentDate}</PaymentStartDate>
				<PaymentFrequency>${paymentFrequency}</PaymentFrequency>
			</RecurringPaymentDate>
		</PaymentDate>
	</PaymentInstruction>
</BPayPaymentRequest>