package com.bt.nextgen.service.integration.options.model;

public enum CategoryType {
    JOB, // USER HIERARCHY
    ADVISER, // USER HIERARCHY
    OFFICE, // USER HIERARCHY
    PRACTICE, // USER HIERARCHY
    DEALER, // USER HIERARCHY
    SUPER_DEALER, // USER HIERARCHY
    STRUCTURE, // PRODUCT HIERARCHY
    ACCOUNT_SUB_TYPE, // PRODUCT HIERARCHY
    OFFER, // PRODUCT HIERARCHY
    WHITE_LABEL, // PRODUCT HIERARCHY
    PRIVATE_LABEL, // PRODUCT HIERARCHY
    PRODUCT;// PRODUCT HIERARCHY
}
